// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfuu3MDoaDsdhFUkzZTkzlXAos_-PlkDs',
    appId: '1:631967077015:web:d97b2923c8a01fb2748fd2',
    messagingSenderId: '631967077015',
    projectId: 'tienda-local-flutter-2024',
    authDomain: 'tienda-local-flutter-2024.firebaseapp.com',
    storageBucket: 'tienda-local-flutter-2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJDNJ_WS4HU-nTN2qaXEolC0rJhLbZyPg',
    appId: '1:631967077015:android:83bc2350bb136a3f748fd2',
    messagingSenderId: '631967077015',
    projectId: 'tienda-local-flutter-2024',
    storageBucket: 'tienda-local-flutter-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlBkYGFQqb1wqCigtSfDlf3T7sWXD2bOQ',
    appId: '1:631967077015:ios:d59d1e5cd730e163748fd2',
    messagingSenderId: '631967077015',
    projectId: 'tienda-local-flutter-2024',
    storageBucket: 'tienda-local-flutter-2024.firebasestorage.app',
    iosBundleId: 'com.example.menusContextuales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlBkYGFQqb1wqCigtSfDlf3T7sWXD2bOQ',
    appId: '1:631967077015:ios:d59d1e5cd730e163748fd2',
    messagingSenderId: '631967077015',
    projectId: 'tienda-local-flutter-2024',
    storageBucket: 'tienda-local-flutter-2024.firebasestorage.app',
    iosBundleId: 'com.example.menusContextuales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfuu3MDoaDsdhFUkzZTkzlXAos_-PlkDs',
    appId: '1:631967077015:web:5460e5b1c5135204748fd2',
    messagingSenderId: '631967077015',
    projectId: 'tienda-local-flutter-2024',
    authDomain: 'tienda-local-flutter-2024.firebaseapp.com',
    storageBucket: 'tienda-local-flutter-2024.firebasestorage.app',
  );
}
